language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # libnds
  # - sudo ./build_libnds_64 > /dev/null
  # - echo "export DEVKITPRO=/opt/devkitpro" >> ~/.bashrc
  # - echo "export DEVKITARM=$DEVKITPRO/devkitARM" >> ~/.bashrc

services:
  - xvfb

script: 
  # Build and run tests
  - ./build_files > /dev/null
  - ./build_console_test > /dev/null
  - ./Console/CityOfThievesConsoleTest > /dev/null
  - ./build_console > /dev/null
  - ./build_desktop > /dev/null
  # Build libnds
  # - travis_wait 40 ./build_nds
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov &> /dev/null
  - codecov &> /dev/null
  # OCLint
  - ./do_oclint || true

after_success:
  - bash <(curl -s https://codecov.io/bash)


