language: cpp
compiler: gcc
dist: trusty

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  # C++14
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # GraphViz
  - sudo apt-get install -qq graphviz
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # libnds
  # From https://github.com/richelbilderbeek/travis_qmake_gcc_cpp98_libnds
  - pwd
  - my_github=${PWD##*/} 
  - echo $my_github
  # Create folder structure
  - sudo mkdir -p /opt/devkitpro
  - sudo chmod 777 /opt/devkitpro
  # Go to that folder
  - cd /opt/devkitpro
  # Download and extract devkitARM
  - sudo wget https://sourceforge.net/projects/devkitpro/files/devkitARM/devkitARM_r47/devkitARM_r47-x86_64-linux.tar.bz2
  # Extract
  - sudo tar -xvjf devkitARM_r47-x86_64-linux.tar.bz2
  # libnds
  - mkdir libnds
  - cd libnds
  - sudo wget https://sourceforge.net/projects/devkitpro/files/libnds/1.7.1/libnds-1.7.1.tar.bz2
  - sudo tar -xvjf libnds-1.7.1.tar.bz2
  # libfat (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/libfat/1.1.2/libfat-nds-1.1.2.tar.bz2
  - sudo tar -xvjf libfat-nds-1.1.2.tar.bz2
  # dswifi (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/dswifi/0.4.0/dswifi-0.4.0.tar.bz2
  - sudo tar -xvjf dswifi-0.4.0.tar.bz2
  # maxmod (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/maxmod/1.0.10/maxmod-nds-1.0.10.tar.bz2
  - sudo tar -xvjf maxmod-nds-1.0.10.tar.bz2
  # libfilesystem (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/filesystem/0.9.13-1/libfilesystem-0.9.13-1.tar.bz2
  - sudo tar -xvjf libfilesystem-0.9.13-1.tar.bz2
  # default_arm7 (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/default_arm7/0.7.3/default_arm7-0.7.3.tar.bz2
  - sudo tar -xvjf default_arm7-0.7.3.tar.bz2
  # Go to /opt/devkitpro
  - cd ..
  # Examples
  - mkdir -p examples/nds
  - cd examples/nds
  - sudo wget https://sourceforge.net/projects/devkitpro/files/examples/nds/nds-examples-20170915.tar.bz2
  - sudo tar -xvjf nds-examples-20170915.tar.bz2

addons:
  apt: 
    packages: libboost-all-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Build and run tests
  - ./build_files
  - ./build_console_test
  - ./Console/CityOfThievesConsoleTest
  - ./build_console
  - ./build_desktop
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Codecov
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)


